# Generated by Django 4.2.9 on 2024-01-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0008_country_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'country'},
        ),
    ]
